spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Java_Laboratory_3_4_5
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: borusovaleks@gmail.com
    password: ycwh rrub livv vpxd
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
logging:
  level:
    sql: info
